### ISSUE TITLE
Apply phylter on clonal data

### ISSUE THREAD

**Issue by bvalot** [damiendevienne/phylter#5] opened 2023-04-06 11:27 UTC
Hi,

I'm currently working on phylogenomic analysis on particular clone of Pseudomonas aeruginosa.
I have some problems of long branch du to potential recombinaison events.

I want to use phylter to detect gene/species link to this long branch, but I have some difficulties to use your tools on this data because the matrix of genetic distance of these genes are mostly compose of 0. 

How can I use your tools on this purpose?

Thanks in advance,
Benoit

**Comment by damiendevienne** [comment] 2023-04-06 11:40
Hello Benoit, 
Can you be more specific on the difficulties you encounter? Is the script unable to handle your data or is it an interpretation issue? 
D

**Comment by bvalot** [comment] 2023-04-06 11:49
I can't use median normalisation, because all my genes have a median value of 0.
I switch to mean with a very low norm.cutoff and I was able to run, but I am not sur that is the correct approach for this type of data.

**Comment by damiendevienne** [comment] 2023-04-06 12:02
Well, I would have had the same approach... 
We didn't test specifically the tool for such kind of sparse matrices. 
To start, you can maybe run phylter with the parameters you mention and check whether the first outliers detected make sense when you look at the trees by eye?

**Comment by bvalot** [comment] 2023-04-06 12:05
Ok, I will try and give you back.

**Comment by bvalot** [comment] 2023-04-06 14:56
Here, the result of analysis:
```
Initial score: 0.06725
    3446  new cells to remove -> New score: 0.07072 -> OK
    4627  new cells to remove -> New score: 0.07342 -> OK
    1449  new cells to remove -> New score: 0.07476 -> OK
    554  new cells to remove -> New score: 0.07473 -> NO
 => Gain too small  ->  Checking for complete gene outliers
    1873  new cells to remove -> New score: 0.07845 -> OK
    599  new cells to remove -> New score: 0.07846 -> OK
    360  new cells to remove -> New score: 0.07857 -> OK
    374  new cells to remove -> New score: 0.07862 -> OK
    142  new cells to remove -> New score: 0.07882 -> OK
    130  new cells to remove -> New score: 0.07884 -> OK
    122  new cells to remove -> New score: 0.07885 -> NO
 => Gain too small  ->  Checking for complete gene outliers
 => No more outliers detected  ->  STOPPING OPTIMIZATION
--------

Total number of outliers detected: 9856
  Number of complete gene outliers : 8
  Number of complete species outliers : 0

Gain (concordance between matrices): 1.16% 
Loss (data filtering): 2% 
```

**Comment by damiendevienne** [comment] 2023-04-06 15:54
oh!!! Well, I've never seen such bad scores! 
This score is a measure of correlation between the input matrices. It goes from 0 to 1. So on your dataset, the matrices seem completely uncorrelated. This is certainly due to the fact the matrices are mainly made of zeros... 

My impression is that PhylteR is not appropriate for this dataset, unless I missed something. 

We can keep talking in private messages if you want. I close the issue for now, as the problem is not related to an error in PhylteR but to a more general question of usability of PhylteR for highly (terribly) sparse datasets.

**Closed as not planned by damiendevienne** 2023-04-06 15:54 UTC
