### ISSUE TITLE
object 'k' not found

### ISSUE THREAD

**Issue by PierreHenriFabre** [damiendevienne/phylter#7] opened 2024-01-09 18:16 UTC
Dear Damien. I am using the package phylter installed on ubuntu machin as well as a windows machine.

I was using the following command on a set of trees. 

if ( exists("alltrees") ) rm(alltrees) ;
alltrees <- read.tree("iqtrees_x476_LEX_thomrod_NT.hybpiper.alltrees");
thom_outlier_hybpiper<-phylter(alltrees,bvalue=0,k=2,k2=k,distance="patristic",Norm="median",Norm.cutoff=0.001,gene.names=NULL, test.island=TRUE,verbose=TRUE,stop.criteria=1e-5, InitialOnly=FALSE,normalizeby="row",parallel=TRUE)

The software return the following message meaning that it was not able to found K (nb: I also tried k=3 and k=2 etc ...)

 => Gain too small  ->  Checking for complete gene outliersError in outl.adj.tuckey(-arr, k = k) : object 'k' not found
In addition: Warning message:
In impMean(matrices) :
90 pairs of species were never found together in trees.
Mean distances were thus infered using their closest neighbors.

This dataset was processed properly on my previously installed version of phylter (phylter v. 0.9.6).
I first thougth it was due to the trees with small amount of tips, I removed them but it did not solve the problem.
 
Thanks so much for your help for developping the phylter software.

All the best

Sincerely
Pierre-Henri Fabre

**Comment by damiendevienne** [comment] 2024-01-10 12:17
Hi Pierre-Henri, 
The problem is finally quite simple. 
You should not explicitly specify `k2=k`. This is the default behavior of the function when k2 is not specified. If you decide to specify it (by typing `k2=x`) in the call to the function, you need `x` to be a variable that has a proper value within your R session. In your case, `k` has no value in the session when you call the function. 

Two workarounds:
 
- remove `k2=k` in the call to the function 
- specify explicitely `k2=2` (in your case, because you set `k=2`)


These two options will produce the same output. 

Hope that helps? 

Damien

**Comment by damiendevienne** [comment] 2024-01-10 12:21
I now close this issue as it is solved.

**Closed as completed** 2024-01-10 12:21 UTC
